---
- name: Check for config dir
  ansible.builtin.stat:
    path: "{{ deluge_config_dir | dirname }}"
  register: _deluge_config_dir
  tags:
    - deluge
    - deluge_config

- name: Create config directory
  ansible.builtin.file:
    path: "{{ deluge_config_dir }}"
    state: directory
    mode: "0700"
    owner: "{{ deluge_service_user }}"
    group: "{{ deluge_service_group }}"
  when:
    - _deluge_config_dir is defined
    - not _deluge_config_dir.stat.exists
  tags:
    - deluge
    - deluge_config
  become: true

- name: Checking if we should template the deluge config file
  ansible.builtin.template:
    src: "{{ deluge_core_conf_template }}"
    dest: "{{ deluge_config_dir }}/core.conf"
    owner: "{{ deluge_service_user }}"
    group: "{{ deluge_service_group }}"
    mode: "0644"
  check_mode: true
  become: true
  notify: Stop deluged
  changed_when: false
  tags:
    - deluge_config

- name: Copy deluge configuration file
  ansible.builtin.template:
    src: "{{ deluge_core_conf_template }}"
    dest: "{{ deluge_config_dir }}/core.conf"
    owner: "{{ deluge_service_user }}"
    group: "{{ deluge_service_group }}"
    mode: "0644"
    backup: true
  become: true
  notify: Restart deluged
  tags:
    - deluge_config

- name: Checking if we should template the deluge-web config file
  ansible.builtin.template:
    src: "{{ deluge_web_conf_template }}"
    dest: "{{ deluge_config_dir }}/web.conf"
    owner: "{{ deluge_service_user }}"
    group: "{{ deluge_service_group }}"
    mode: "0644"
  check_mode: true
  become: true
  notify: Stop deluge-web
  changed_when: false
  tags:
    - deluge_config

- name: Copy deluge-web configuration file
  ansible.builtin.template:
    src: "{{ deluge_web_conf_template }}"
    dest: "{{ deluge_config_dir }}/web.conf"
    owner: "{{ deluge_service_user }}"
    group: "{{ deluge_service_group }}"
    mode: "0644"
    backup: true
  become: true
  notify: Restart deluge-web
  when: deluge_web
  changed_when: false
  tags:
    - deluge_config
