---
- name: Stop deluged
  ansible.builtin.systemd:
    name: deluged
    state: stopped
  become: true

- name: Stop deluge-web
  ansible.builtin.systemd:
    name: deluge-web
    state: stopped
  become: true

- name: Restart deluged
  ansible.builtin.systemd:
    name: deluged
    state: restarted
  become: true

- name: Restart deluge-web
  ansible.builtin.systemd:
    name: deluge-web
    state: restarted
  become: true
